set_property IOSTANDARD LVCMOS33 [get_ports Clk]
set_property PACKAGE_PIN W5 [get_ports Clk]

set_property PACKAGE_PIN U16 [get_ports {RxData[0]}]
set_property PACKAGE_PIN E19 [get_ports {RxData[1]}]
set_property PACKAGE_PIN U19 [get_ports {RxData[2]}]
set_property PACKAGE_PIN V19 [get_ports {RxData[3]}]
set_property PACKAGE_PIN W18 [get_ports {RxData[4]}]
set_property PACKAGE_PIN U15 [get_ports {RxData[5]}]
set_property PACKAGE_PIN U14 [get_ports {RxData[6]}]
set_property PACKAGE_PIN V14 [get_ports {RxData[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RxData[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RxData[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RxData[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RxData[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RxData[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RxData[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RxData[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {RxData[0]}]
# set_property PACKAGE_PIN L1 [get_ports rxDone]
set_property PACKAGE_PIN K17 [get_ports Rx]
# set_property IOSTANDARD LVCMOS33 [get_ports rxDone]
set_property IOSTANDARD LVCMOS33 [get_ports Rx]

set_property PACKAGE_PIN U18 [get_ports buttonMiddle]
set_property IOSTANDARD LVCMOS33 [get_ports buttonMiddle]
